# e_arima()

e_arima<-function(explaining=0){
if(explaining==0) {
cat(" setwd('F:/dataEviews') ", '\n')
cat(" library(readxl);library(forecast);library(strucchange);library(changepoint);library(r412) ", '\n')
cat(" Adata<-read_excel('Eviews2_2.xlsx') ", '\n')
cat(" gdp_sa<-ts(Adata$gdp_sa, start=c(1960,1), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" plot을 보니, 1960년대 이후자료라서 자료를 나누는 것을 고려 ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" e_structuralbreak(0) ", '\n')
cat(" library(strucchange);library(changepoint); library(tidyverse); library(lubridate) ", '\n')
cat(" Result02 <- cpt.meanvar(dlog(gdp_sa), method = 'PELT') ", '\n')
cat(" plot(Result02) # plot을 확인한 결과, 2020년대 이후자료만 고려하기로 ", '\n')
cat(" gdp_sa2<-window(gdp_sa, start=c(2000,1), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" ident(gdp_sa2) ", '\n')
cat(" ndiffs(gdp_sa2) ", '\n')
cat(" 1차 difference를 해야 stationary가 됨 ", '\n')
cat(" graphics.off() ", '\n')
cat(" plot(diff(gdp_sa2)) ", '\n')
cat(" ident(diff(gdp_sa2), 33) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(1,1,0),include.drift=T,method='ML') ) ", '\n')
cat(" summary(Arima(gdp_sa2, order=c(0,1,1), seasonal=c(0,0,2),include.drift=T, method='ML')) ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(0,1,1),seasonal=c(0,0,2),fixed=c(NA,0,NA,NA),include.drift=T,method='ML')) ", '\n')
cat(" 			 ", '\n')
cat(" summary(auto.arima(gdp_sa2, method='ML')) ", '\n')
cat(" Eviews의 결과 형식과 R의 결과 형식은 동일함. 동일한 방법으로 모형의 기록/해석 가능 ", '\n')
cat(" R1<-Arima( (gdp_sa2), order=c(1,1,1), method='ML')  ", '\n')
cat(" checkresiduals(R1)  ", '\n')
cat(" qstat(R1)  ", '\n')
cat(" forecast(R1, h=5)  ", '\n')
cat(" 			 ", '\n')
cat(" R2 <- Arima( log(gdp_sa), order=c(1,1,1), ", '\n')
cat("              seasonal=list(order=c(1,1,0), period=4), method='ML' )  ", '\n')
cat(" R3 <- auto.arima( diff(log(gdp_sa2)), seasonal=FALSE, method='ML' )  ", '\n')
cat(" Simul <- arima.sim(model = list(ar=0.5, ma=0.3), n=100) ", '\n')
}}
