e_VAR<-function(explaining=0){
if(explaining==0) {
cat("library(vars); library(readxl)", '\n')
cat("Bdata<-read_excel('eviews8.xlsx')", '\n')
cat("전세가율<-ts(Bdata$전세가율, start=c(2013,1), frequency=12)", '\n')
cat("# frequency의 표시 -------------  ", '\n')
cat("Annual: frequency=1", '\n')
cat("Quarterly: frequency=4 ", '\n')
cat("Monthly: frequency=12 ", '\n')
cat("Weekly: frequency=52 ", '\n')
cat("       ", '\n')
cat("# Dataset 설정 -------------  ", '\n')
cat("전세가율 <- ts(Bdata$전세가, start=c(2013,1), frequency=12)", '\n')
cat("매매가 <- ts(Bdata$매매가, start=c(2013,1), frequency=12)", '\n')
cat("Bdata <- cbind(매매가, 전세가율)", '\n')
cat("Bdata <- as.data.frame(Bdata)", '\n')
cat("       ", '\n')
cat("# Lag의 결정 ---------------  ", '\n')
cat("Re.info <- VARselect(Bdata[,c(1:2)], lag.max=5, type='const')", '\n')
cat("## type = const, trend, both, none  ", '\n')
cat("Re.info$selection", '\n')
cat("       ", '\n')
cat("# Lag의 자동결정 ---------------  ", '\n')
cat("Re1 <- VAR(Bdata[,c(1:2)], type='const', lag=2) # auto selecting lags ", '\n')
cat("Re2 <- VAR(Bdata[,c(1:2)], type='const', p=2) # designating lags", '\n')
cat("       ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# VAR분석 ---------------  ", '\n')
cat("Re.var<-VAR(Bdata[,c(1:2)], p=1, type='const')", '\n')
cat("## type = const, trend, both, none  ", '\n')
cat("       ", '\n')
cat("# 그랜저 인과관계 분석 ---------------  ", '\n')
cat("Re.Cause.gni_pc<-causality(re.var, cause='gni_pc')", '\n')
cat("Re.Cause.m2_pc <- causality(re.var, cause='m2_pc')", '\n')
cat("       ", '\n')
cat("# 충격반응함수(Impulse Response Function)------------- ", '\n')
cat("# 충격반응함수: 한 변수의 충격이 다른 변수에 몇 기간 동안 영향을 미치는지 보여준다 ", '\n')
cat("IRF.gni<-irf(Re2, impulse='m2_pc', response='gni_pc', ", '\n')
cat("             n.ahead=40, boot=TRUE) ", '\n')
cat("plot(IRF.gni, ylab='GNI반응', main='M2 Shock') ", '\n')
cat("IRF.M2<-irf(Re2, impulse='gni_pc', response='m2_pc', ", '\n')
cat("             n.ahead=40, boot=TRUE) ", '\n')
cat("plot(IRF.M2, ylab='M2반응', main='GNI Shock') ", '\n')
cat(" 				 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("                ", '\n')
cat("# 예측오차분산분해(Forecasting Error Variance Decomposition)--------- ", '\n')
cat("# 예측오차분산분해: 한 변수의 충격 변동이 다른 변수 변동에 몇 %퍼센트 영향을 미치는지 상대적 중요도를 보여준다. ", '\n')
cat("Re2.decomp<-fevd(Re2, n.ahead=10) ", '\n')
cat("Re2.decomp ", '\n')
cat("     ", '\n')
cat("     ", '\n')
cat("# 예측치의 작성 ------------------     ", '\n')
cat("predictions <- predict(Re2, n.ahead=8, ci=0.95 ) ", '\n')
cat(" 				 ", '\n')
cat("# SVAR-A model------------- ", '\n')
cat("amat <- diag(1, 2) ", '\n')
cat("amat[lower.tri(amat)] <- NA ", '\n')
cat("svar_Amodel <- SVAR(Re1, Amat = amat, max.iter = 1000) ", '\n')
cat("svar_Amodel ", '\n')
cat("svar_Bmodel=solve(svar_Amodel) ", '\n')
cat(" 				 ", '\n')
cat("# SVAR-B model------------- ", '\n')
cat("bmat <- diag(1, 2) ", '\n')
cat("bmat[lower.tri(bmat)] <- NA ", '\n')
cat("svar_Bmodel <- SVAR(Re1, Bmat = bmat) ", '\n')
cat("svar_Bmodel ", '\n')
}}

