# e_VECM()

e_VECM<-function(explaining=0){
if(explaining==0) {
cat("------------------------------------------------------------------------ ", '\n')
cat("(1) lag길이 결정       ", '\n')
cat("VARselect(dat.VAR, lag.max=5, type='const') ", '\n')
cat("## type = const, trend, both, none  ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat("(2) 공적분 점검         ", '\n')
cat("ca.jo(x, type = c('trace', 'eigen'), ecdet = c('none', 'const', 'trend'), K=2)", '\n')
cat("## K=2(Lag갯수), spec=c('longrun', 'transitory') ", '\n')
cat("## K=2 : lag order of the series (levels) in the VAR ", '\n')
cat("## season = NULL, dumvar = NULL) ", '\n')
cat("## spec : longrun=요한센모형 : transitory=변형된 요한센모형, '\n') ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat("(3) VECM모형 실행     ", '\n')
cat("Result<-VECM(dat.VAR, lag=1, r=1, estim = 'ML', LRinclude = 'none')", '\n')
cat("## r=1 => I(1) , estim = c('2OLS', 'ML'), LRinclude => 2OLS only  ", '\n')
cat("------------------------------------------------------------------------ ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("(1)-(3)의 통합 실행       ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat("library(tsDyn);library(vars); library(readxl)", '\n')
cat("Adata<-read_excel('Eviews13.xlsx')", '\n')
cat("lexpen<-ts(Adata$lexpen, start=c(1985,1), frequency=4)", '\n')
cat("lgni<-ts(Adata$lgni, start=c(1985,1), frequency=4)", '\n')
cat("dat.VAR<-cbind(lexpen, lgni)", '\n')
cat("       ", '\n')
cat("VARselect(dat.VAR, lag.max=5, type='const') ", '\n')
cat("       ", '\n')
cat("johansen결과 <- ca.jo(dat.VAR, type = c('trace'), ecdet = c('none'), K = 2)", '\n')
cat("summary(johansen결과) ", '\n')
cat("       ", '\n')
cat("Result<-VECM(dat.VAR, lag=1, r=1, include='const', estim = 'ML', LRinclude = 'none') ", '\n')
cat("summary(Result) ", '\n')
cat("       ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("VAR결과<-vec2var(johansen결과, r=1)", '\n')
cat("# Serial Correlation -------- ", '\n')
cat("serial1<-serial.test(VAR결과, lags.pt=5, type='PT.asymptotic')", '\n')
cat("     ", '\n')
cat("## Arch effects --------  ", '\n')
cat("Arch1 <- arch.test(VAR결과, lags.multi=15, multivariate.only=TRUE)", '\n')
cat("   ", '\n')
cat("## Normality of Residuals --------", '\n')
cat("Normal1 <-normality.test(VAR결과, multivariate.only=TRUE)", '\n')
cat("    ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("         ", '\n')
cat("## 충격반응함수(IRF): B의 충격이 A의 변동을 몇 기간에 걸쳐서 영향을 주는가?    ", '\n')
cat("IRF.lexpen<-irf(VAR결과,impulse='lgni',response='lexpen',n.ahead=20, boot=TRUE)", '\n')
cat("plot(IRF.lexpen, ylab='lexpen', main='GNI shock to Expen')", '\n')
cat("IRF.lgni<-irf(VAR결과,impulse='lexpen',response='lgni', n.ahead=20, boot=TRUE)", '\n')
cat("plot(IRF.lgni, ylab='GNI', main='Expenditure shock to GNI')", '\n')
cat("         ", '\n')
cat("## 예측오차분산분해: B의 충격이 몇 %의 비율로 A의 변동을 설명하는가? 상대적 중요도를 보여준다.   ", '\n')
cat("## Forecasting Error Variance Decomposition ---", '\n')
cat("FEVD1 <- fevd(VAR결과, n.ahead=20 )", '\n')
cat("plot(FEVD1)", '\n')
cat("FEVD1", '\n')
cat("         ", '\n')
cat("## 예측치 구하기(Predictions)--------", '\n')
cat("predictions <- predict(VAR결과, n.ahead=5, ci=0.95 )", '\n')
cat("predictions", '\n')
}}
